### ISSUE TITLE
Prefer Fast Workers

### ISSUE THREAD

**Issue by MarkSchmidty** [db0/KoboldAI-Horde#28]
Preference should be **explicitly** given to the fastest available workers. This does two things:
1. Incentivizes workers to make horde faster over time by incentivizing increasing inference speed to get more kudos
2. Creates a better, faster, user experience for horde users.

The current behavior results in poor user experiences using horde and poor incentives for horde workers to improve their configurations, despite the fact that fast workers get slightly more jobs due to clearing jobs more quickly.

**Comment by db0** [comment]
Preference is given to the fastest workers by design. As they pull requests faster.

**Comment by MarkSchmidty** [comment]
> Preference is given to the fastest workers by design. As they pull requests faster.

While it's true that faster workers clear jobs faster and thus get more jobs, it is not the case that they given any kind of preference.

If they were given explicit preference they would be chosen over slower workers when the group of idle workers contains slow and fast workers. This would resolve the issues raised in the OP.

The current behavior does not resolve those two issues. Instead it results in poor user experiences using horde and poor incentives for horde workers to improve their configurations.
